tap "homebrew/bundle"
# tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
# tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "mas"
brew "coreutils"
brew "binutils"
brew "diffutils"
brew "ed"
brew "findutils"
brew "gawk"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "make"
brew "gzip"
brew "wget"
brew "gpg"
brew "htop"
brew "eza"
brew "ripgrep"
brew "ncdu"
brew "diff-so-fancy"
brew "go"
brew "libpq"
brew "nvm"

cask "iterm2"
cask "karabiner-elements"
cask "hammerspoon"
cask "notion"
cask "standard-notes"
cask "forklift"
cask "visual-studio-code"
cask "google-chrome"
cask "slack"
cask "alfred"
cask "viscosity"
cask "keepingyouawake"
cask "numi"
cask "adobe-acrobat-reader"
cask "adobe-creative-cloud"
cask "google-drive"
cask "zoom"
cask "dbeaver-community"
cask "transmission"
cask "docker"
cask "anydesk"
cask "microsoft-office"
cask "whatsapp"
cask "telegram"
cask "fantastical"

mas "paste", id:967805235
mas "Microsoft Remote Desktop", id:1295203466
mas "BetterSnapTool", id:417375580
